/**
 * Het decor van de wei, in pixelkunst: wat een dier nodig heeft (wei.ts),
 * en de grasrand als tegel die zich herhaalt. Gegenereerd uit eenvoudige
 * vormen, met licht van linksboven,
 * schaduw onderaan en een omlijning in een donkere tint, net als de dieren.
 * Een letter is een kleur uit het palet, een punt is leeg; 32 pixels is 1em.
 */

export interface Decorplaatje {
  rijen: readonly string[];
  palet: Readonly<Record<string, string>>;
}

export const DECOR: Readonly<Record<string, Decorplaatje>> = {
  boom: {
    palet: { 'a': '#2a3837', 'b': '#79ac6c', 'c': '#4c9446', 'd': '#6fb85f', 'e': '#61a058', 'f': '#478744', 'g': '#e24a3b', 'h': '#427a42', 'i': '#387836', 'j': '#684633', 'l': '#7b5334', 'm': '#326335', 'n': '#382431', 'o': '#714c34', 'p': '#242f32', 'q': '#8b6748', 'r': '#9c7c5e', 's': '#5e3d25' },
    rijen: [
      '.........................aaaaaaaa.........................',
      '.......................aabbbbbbbbaa.......................',
      '.....................aabbccccccccbbaa.....................',
      '....................abbccccccccccccbba....................',
      '................aaaabcccccddddddcccccba...................',
      '.............aaabbbbccccccddddddccccccbaaa................',
      '............abbbccccccccccddddddcccccccbbbaa..............',
      '..........aabcccccccccccccddddddccccccccccbbaa............',
      '.........abbccccccddddccccccccccccccccccccccbba...........',
      '.........aeccccccddddddcccccccccccccccccccccccba..........',
      '........abccccccddddddddcccccccccddddddccccccccba.........',
      '.......abcccccccddddddddcccccccccddddddcccccccccba........',
      '.......aeccccccccddddddccccccccccddddddcccccccccfa........',
      '......abccccccccccddddcccccccccccddddddccccccccccba.......',
      '......aecccccccccccccccccccccccccccccccccccccccccfa.......',
      '......aecccccccccccccccccccccccccccccccccccccccccfa.......',
      '......aecccccccccccccccccccccccggccccccccccccccccfa.......',
      '......aecccccccccccccccccccccccggccccccccccccccccfa.......',
      '......ahccccccccccccccccddcccccccccccccccccccccccha.......',
      '.......aeccccccccccccccddddcccccccccccccccccccccfa........',
      '.......ahccccccccccccccddddcccccccccccccccccccccfa........',
      '........aecddddcccccccccddccccccccccccccccccccccfa........',
      '.......abcddddddcccccccccccccccccccccggccccccccccba.......',
      '.......aecddddddcccccccccccccccccccccggccccccccccfa.......',
      '......abcccddddcccccccccccccccccccccccccccccccccccba......',
      '.....abcccccccciiiiccccccccccccccccccciiiicccccccccba.....',
      '....abcccccccciiiiiiccccccccccccccccciiiiiicccccccccba....',
      '...abccccccccciiiiiiccccccccccccccccciiiiiiccccccccccba...',
      '..abccccccccccciiiiccccccccccccccccccciiiiccccccccccccba..',
      '.abccccccccccccggccccccccccccccccccccccccccccccccccccccba.',
      '.aeccccccccccccggccccccccciiiicccccccccccccccggccccccccfa.',
      '.aecccccccccccccccccccccciiiiiiccccccccccccccggccccccccfa.',
      '.aecccccccccccccccccccccggiiiiiicccccccccccccccccccccccfa.',
      '.aeccccccciiiiccccccccccggiiiiiicccccccccccciiiicccccccfa.',
      '.ahcccccciiiiiicccccccccciiiiiicccccccccccciiiiiiccccccha.',
      '..ahcccciiiiiiiiccciiiiiiciiiicciiiiiicccciiiiiiiiccccha..',
      '...ahccciiiiiiiiciiiiiiiiiiccciiiiiiiiiicciiiiiiiicccha...',
      '....ahccciiiiiicciiiiiiiiiiccciiiiiiiiiiccciiiiiicccha....',
      '.....ahccciiiiccciiiiiiiiiiccciiiiiiiiiicccciiiicccha.....',
      '......ahhhccccccciiiiiiiiiiccciiiiiiiiiicccccccchhha......',
      '.......aaahhhhhhhhjllllimccccccciiilllljhhhhhhhhaaa.......',
      '..........aaaaaaaanjlllopqlllllllllllljnaaaaaaaa..........',
      '...................nqlllrllsllllllllljn...................',
      '...................njllllllslllllllljn....................',
      '....................njlllllslllllljjn.....................',
      '.....................njlllllllllljnn......................',
      '......................njllllllllon........................',
      '.......................njlllllllon........................',
      '........................nqllllllon........................',
      '........................nqllllslon........................',
      '........................nqllllslon........................',
      '........................nqllllslon........................',
      '........................nqlsllllon........................',
      '........................nqlsllllon........................',
      '........................nqlsllslon........................',
      '........................nqllllslon........................',
      '........................nqllllslon........................',
      '........................nqlsllllon........................',
      '........................nqlsllllon........................',
      '........................nqlsllslon........................',
      '........................nqllllslon........................',
      '........................nqllllslon........................',
      '........................nqlsllllon........................',
      '........................nqlsllllon........................',
      '........................nqlsllslon........................',
      '........................nqllllslon........................',
      '.......................nnqllllslon........................',
      '......................nrrllllllllrn.......................',
      '.....................nrlllllllllllrn......................',
      '.....................njjjjjjjjjjjjjn......................',
    ],
  },
  bananenboom: {
    palet: { 'a': '#2e3e37', 'b': '#212b2e', 'c': '#253331', 'd': '#83bc6c', 'e': '#2f6a2a', 'f': '#6da25e', 'g': '#5aa846', 'h': '#3c8634', 'i': '#549944', 'j': '#4d8a42', 'l': '#356e33', 'm': '#539348', 'n': '#397a34', 'o': '#9c7b56', 'p': '#8f6a44', 'q': '#6d4e30', 'r': '#342330', 's': '#7f6245', 't': '#836142', 'u': '#3e2b36', 'v': '#785840', 'w': '#5d4a34', 'x': '#f8d651', 'y': '#f7d23e', 'z': '#ab8d6a', 'A': '#f9db66', 'B': '#92785b', 'C': '#e1bf3d', 'D': '#d8a11c', 'E': '#c5921e', 'F': '#543c2a', 'G': '#cbab3b', 'H': '#b28420' },
    rijen: [
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '...............................aaabb......................',
      '......................cc....c.adddeeba....................',
      '.................ccbccffccbcfcdgeehebdaa.a................',
      '................cffefehhffeehdgeghibdgddadaba.............',
      '..............bbeeebjgeeeheggggggggdeeeeeeeedab...........',
      '.............beejbbjajgggehhghggggeehlhllllbleeb..........',
      '..............bbacfafamhhhhhhhggggggnclcccc.cbbeb.........',
      '................ccmfhfhhhhhhhhgggggggdca.a.....b..........',
      '..............ccffehhheeeeeeeeeeeeeeegddada...............',
      '............ccfejghheejggggggghhhhhhleeediaa..............',
      '..........ccfeeiameejjajjjgggghhhhllcllheebda.............',
      '.........cfeejbmeejjaa.aaaopggqqplcc.ccllheeba............',
      '........bbejbabebbaa.....rsqqqqqtc.....cclbledaa..........',
      '.......beebacfeja........uvpppqqtu.wr....c.cbeeda.........',
      '......bebb.beeba..........uxqpqyqzuABr......clbeb.........',
      '.......b..bebb...........wAyyyyyyyAyyAw......ccleb........',
      '.........beb.............wxyyyyyyyyyyCw........cbeb.......',
      '..........b..............wxyyDyyyDyyyEF..........beb......',
      '........................wAqyyyqyyyqyGHF...........b.......',
      '.......................wAyyyyyyyyyyCwF....................',
      '.......................wxyyyyyyyyyyCw.....................',
      '.......................wGyyDyyyDyyyEF.....................',
      '........................wGGHpyqDpyyHF.....................',
      '.........................wwFxyyypptF......................',
      '...........................wxyyyqqtu......................',
      '...........................wxyyDpptu......................',
      '...........................uoyyDpptu......................',
      '...........................uoppppptu......................',
      '...........................rsqqqqqtu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................rsqqqqqtu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................rsqqqqqtu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................uoppppptu......................',
      '...........................rsqqqqqtu......................',
      '...........................uopppppvu......................',
      '..........................uzppppptu.......................',
      '..........................uoppppptu.......................',
      '..........................rsqqqqqtu.......................',
      '..........................uoppppptu.......................',
      '..........................uopppppvu.......................',
      '.........................uzppppptu........................',
      '.........................rsqqqqqtu........................',
      '.........................uoppppptu........................',
      '.........................uopppppvu........................',
      '........................uzppppptu.........................',
      '........................rsqqqqqtu.........................',
      '......................uuzpppppptuu........................',
      '.....................uzzppppppppzzu.......................',
      '.....................uvvvvvvvvvvvvu.......................',
    ],
  },
  vijver: {
    palet: { 'a': '#3c262f', 'b': '#a7815a', 'c': '#986d43', 'd': '#7f532e', 'e': '#744b2e', 'f': '#487e39', 'g': '#2a3533', 'h': '#263032', 'i': '#6f995f', 'j': '#3f7a35', 'l': '#8f8a80', 'm': '#62974d', 'n': '#b5afa3', 'o': '#3f86c9', 'p': '#a5d6f7', 'q': '#5aa846', 'r': '#386534', 's': '#2d6aa3', 't': '#ff8fb8', 'u': '#787270', 'v': '#22527f', 'w': '#3e3548' },
    rijen: [
      '................................................................................................................................',
      '................................................................................................................................',
      '......................................................................................................................aa........',
      '........a............................................................................................................abba.......',
      '.......aba...........................................................................................................acda.......',
      '.......ada...........................................................................................................acda.......',
      '.......ada...........................................................................................................aeda.......',
      '....aa.ada............................................................................................................afg.a.....',
      '...abbagfg..........................................................................................................a.gfgaba....',
      '...acdagfgaa.......................................................................................................abagfgada....',
      '...acdagfgbba......................................................................................................adagfgada....',
      '...aedagfgcda......................................................................................................adagfgada....',
      '....afggfgcda..............................hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh..............................adagfggfg....',
      '....gfggfgeda................hhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiihhhhhhhhhhhhhh................gfggfggfg....',
      '....gfggfgafg.......hhhhhhhhhiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjiiiiiiiiiiiiiihhhhhhhhh.......gfggfggfg....',
      '....gfggfggfg.hhhhhhiiiiiiiiijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjiiiiiiiiihhhhhh.gfggfggfg....',
      '....gfggfggfghiiiiiijjjjjjjjjjjjjjjjjjjlllllllllllllllllllllllllllllllllllllllllllllllllljjjjjjjjjjjjjjjjjjjiiiiiihgfggfggfg....',
      '....gfggmiijiijjjjjjjjjjjjjlnlllllllllllnlllllllllllnlllllllllllnlllllllllllnlllllllllllnlllllllllllnjjjjjjjjjjjjjiijiifggfg....',
      '...hgmiijjjjjjjjjjjlllnlllllllllllnlllllllllllnoooooooooooooooooooooooooooooooooolnlllllllllllnlllllllllllnlljjjjjjjjjjjiifgh...',
      '..hiijjjjjjjjllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllljjjjjjjjiih..',
      '.hijjjjjjjllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllljjjjjjjih.',
      'hijjjjjlllllllloooooooooppppppppoooooooooooooooooooooooooooooooooooooooooooooopppppppppooooooooooqqqqqqoooooooooolllllllljjjjjih',
      'hrjjjjlllllloooooooooooooooooqqqqqqooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooqqqqqqooooooooooooolllllljjjjrh',
      '.hrjjjlllloooooooooooooooooooqqqqqqossssssssssssssppppppssssssssssssssssssssssssssssssttssssoooooooooooooooooooooooooolllljjjrh.',
      '..hrrrjllloooooooooooooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssqqqttqsssssppppppssssoooooooooooooollljrrrh..',
      '...hhhrrrjllooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssqqqqqqssssssssssssssssssssooooooolljrrrhhh...',
      '......hhhrrrrulooosssssssssssssssssssspppppsssssssssvvvvvvvvvvvvvvvvvvvvvvvvssssssssssssssssssssssssssssssssssooolurrrrhhh......',
      '.........hhhhwrrrrrulssssssssssvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvsssssssssslurrrrrwhhhh.........',
      '..............hhhhhwrrrrrrruulvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvluurrrrrrrwhhhhh..............',
      '....................hhhhhhhwwrrrrrrrrrruuuuuuuuvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvuuuuuuuurrrrrrrrrrwwhhhhhhh....................',
    ],
  },
  bloemen: {
    palet: { 'a': '#49356e', 'b': '#9673d6', 'c': '#5f4a34', 'd': '#d1ab3c', 'e': '#f5a524', 'f': '#3f7a35', 'g': '#a680ea', 'h': '#5f3157', 'i': '#263032', 'j': '#3b6f34', 'l': '#d16899', 'm': '#e8bf3e', 'n': '#5d5468', 'o': '#cbc6c5', 'p': '#e873a6', 'q': '#e1dcd7', 'r': '#2a3837', 's': '#79ac6c', 't': '#568949', 'u': '#4c9446', 'v': '#387836', 'w': '#427a42', 'x': '#326335', 'y': '#242f32' },
    rijen: [
      '................................................',
      '................................................',
      '.......................a........................',
      '......................aba.......................',
      '...........c.........ababa.........c............',
      '..........cdc.......abaeaba.......cdc...........',
      '.........cdcdc.......abfba.......cdcdc..........',
      '........cdcecdc.......aga....h..cdcecdc.........',
      '.....h...cdfdc........iji...hlh..cdfdc..........',
      '....hlh...cmc....n....iji..hlhlh..cmc....a......',
      '...hlhlh..iji...non...iji.hlhehlh.iji...aba.....',
      '..hlhehlh.iji..nonon..iji..hlflh..iji..ababa....',
      '...hlflh..iji.nonenon.iji...hph...iji.abaeaba...',
      '....hph...iji..nofon..iji...iji...iji..abfba....',
      '....iji...iji...nqn...iji...iji...iji...aga.....',
      '....iji...iji...iji...iji...iji...iji...iji.....',
      '....iji...iji...iji...iji...iji...iji...iji.....',
      '....iji...iji...ijirrrijirrriji...iji...iji.....',
      '....ijirrrijir..ijissssfsssssjir..ijirrriji.....',
      '....itsssssfssrrsfsuuuufuuuuufssrrsfsssssjir....',
      '...rsfuuuuufuussufuuuuufuuuuufuussufuuuuufssr...',
      '..rsufuuuuufuuuuufuuuuufuuuuufuuuuufuuuuufuusr..',
      '.rsuuuuuuuuuuuuuuuvvvvvvvvvvvvuuuuuuuuuuuuuuusr.',
      '.rwuuuvvvvvvvvvuuvvvvvvvvvvvvvuuuuvvvvvvvvvvuwr.',
      '..rwuvvvvvvvvvvvwwxvvvvvvvvvvxxwuvvvvvvvvvvvxr..',
      '...rwwxxxxxxxxxxrrywwwwwwwwwwyyrwwxxxxxxxxxxy...',
    ],
  },
  moestuin: {
    palet: { 'a': '#2e3e37', 'b': '#83bc6c', 'c': '#6eb158', 'd': '#334539', 'e': '#5aa846', 'f': '#91cd72', 'g': '#4d8a42', 'h': '#549944', 'i': '#a6e07a', 'j': '#6cbf4f', 'l': '#7ec660', 'm': '#64ae4c', 'n': '#33202c', 'o': '#5c352e', 'p': '#f6973f', 'q': '#df7e2b', 'r': '#907051', 's': '#f58a2a', 't': '#6b4423', 'u': '#5b3a26', 'v': '#533219', 'w': '#482b1e', 'x': '#2c1a29' },
    rijen: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '......a.........a...............a.........a.....',
      '.....aba.......aba.............aba.......aba....',
      '....aacba.....aacba..dddddd...aacba.....aacba...',
      '...abaceba...abacebadffffffd.abaceba...abaceba..',
      '...agbeeha...agbeehafiiiiiifdagbeeha...agbeeha..',
      '....aceega....aceegfjiiiiiijfdaceega....aceega..',
      '....aceha.....acehaljiiiiiijmdaceha.....aceha...',
      '....ageha.....agehaljiiiiiijmdageha.....ageha...',
      '.....acha....nnachaljjjjjjjjmdnacha......acha...',
      '.....opqonnnnrrrssrtjjjjjjjjtrrrssrnnnnnnopqo...',
      '...nnopsrrrrrtttsstttjjjjjjtttttsstrrrrrrrsqo...',
      '.nnrrrssttttttttssttttttttttttttssttttttttssrnn.',
      'nrrttttttttttttttttttttttttttttttttttttttttttrrn',
      'nuuvvvvvvvtttvvvvvvvtttttttttvvvvvvvtttvvvvvvwun',
      '.nnuuuttttttttttttttttttttttttttttttttttttuuuxn.',
      '...nnnuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuunnn...',
    ],
  },
  hol: {
    palet: { 'a': '#382431', 'b': '#412c36', 'c': '#9b7b5e', 'd': '#b38f6b', 'e': '#9a6d45', 'f': '#7a5234', 'g': '#1c120c', 'h': '#9a958a', 'i': '#8a6648', 'j': '#704b34', 'l': '#674533', 'm': '#817a78' },
    rijen: [
      '............................',
      '............................',
      '............................',
      '............................',
      '.......aabbbbbbaaaaaa.......',
      '....aaaccddddddccccccaaa....',
      '...accceeeeeeeeeeffffccca...',
      '..acfffffeeeeeefffffffffca..',
      '.acfffffffffggggfffffffffca.',
      'acfffffffggggggggggfffffhfca',
      'aifhffffggggggggggggffffffja',
      'allllllggggggggggggggmllllla',
    ],
  },
  cactus: {
    palet: { 'a': '#5f3157', 'b': '#ff7eb3', 'c': '#ffd23f', 'd': '#2a3837', 'e': '#61a058', 'f': '#478744', 'g': '#79ac6c', 'h': '#4c9446', 'i': '#387836', 'j': '#b8e09a', 'l': '#427a42' },
    rijen: [
      '............................',
      '............aaaa............',
      '...........abbbba...........',
      '..........abbbcbba..........',
      '..........debbbbfd..........',
      '.........dghhhhhhgd.........',
      '.........dehihhhifd.........',
      '.........dehihhhifd.........',
      '.........dehihhhihgd........',
      '.........dejihhhijfd...d....',
      '.........dehihhhihfd.ddgdd..',
      '.........dehihhhihfddgghggd.',
      '.........dehihhhihfddehhhfd.',
      '....d....dejihhhijfddehhhfd.',
      '..ddgdd..dehihhhihfddehhjfd.',
      '.dgghggd.dehihhhihfddehhhfd.',
      '.dehihfd.dehihhhihfddehihfd.',
      '.dehihfd.dejihhhijfddehihfd.',
      '.dejihfd.dehihhhihfddehijfd.',
      '.dehihfd.dehihhhihfddehihfd.',
      '.dehihfd.dehihhhihfddehihfd.',
      '.dehihfd.dejihhhijfddehihfd.',
      '.dejihfd.dehihhhihfddehijfd.',
      '.dehihfd.dehihhhihhgghhihfd.',
      '.dehihfd.dehihhhihhhhhhihfd.',
      '.dehihfd.dejihhhijhhhhhihfd.',
      '.dejihfd.dehihhhihhhhhhihfd.',
      '.dehhhfdddehihhhihhllllllld.',
      '.dehhhhggghhihhhihfddddddd..',
      '.dehhhhhhhhjihhhijfd........',
      '.dehhhhhhhhhihhhihfd........',
      '.dehhhhhhhhhihhhihfd........',
      '.dllllllllhhihhhihfd........',
      '..ddddddddejihhhijfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dejihhhijfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dejihhhijfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dehihhhihfd........',
      '.........dllllllllld........',
    ],
  },
};

/** De grasrand onder de wei: een tegel die zich herhaalt. */
export const TEGELS: Readonly<Record<string, Decorplaatje>> = {
  grond: {
    palet: { 'a': '#6fb85f', 'b': '#4c9446', 'c': '#3a7a37', 'd': '#4a3220' },
    rijen: [
      '...a......a......a.......a...a..',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'cccccccccccccccccccccccccccccccc',
      'dddddddddddddddddddddddddddddddd',
      'dddddddddddddddddddddddddddddddd',
    ],
  },
};
