/**
 * Het decor van de wei, in pixelkunst: wat elk dier meeneemt (wei.ts).
 * Gegenereerd uit eenvoudige vormen; een letter is een kleur, k de omlijning.
 */

export interface Decorplaatje {
  rijen: readonly string[];
  palet: Readonly<Record<string, string>>;
}

export const DECOR: Readonly<Record<string, Decorplaatje>> = {
  boom: {
    palet: { k: '#23171a', b: '#7a5236', B: '#5c3b25', g: '#4f9a4a', G: '#3a7a37', l: '#79c26a', r: '#e0453a' },
    rijen: [
      '..................................................',
      '.....................kkkkkkkk.....................',
      '..................kkkggggggggkkk..................',
      '................kkggggggggggggggkk................',
      '..............kkggggggggggggggggggkk..............',
      '.............kggggggggggggggggggggggk.............',
      '............kgggllllllgggggggggggggggk............',
      '...........kggllllllllllggggggggggggggk...........',
      '...........kgllllllllllllgggggggggggggk...........',
      '..........kgllllllllllllllgggggggggggggk..........',
      '..........kgllllllllllllllgggggggggggggk..........',
      '..........kggllllllllllllggggggggggggggk..........',
      '..........kgggllllllllllgggggggggggggggk..........',
      '.........kggggggllllllggggggggggggggggggk.........',
      '........kggggggggggggggggggllllllggggggggk........',
      '.......kgggggggggggggggggllllllllllgggggggk.......',
      '......kgggggggggggggggggllllllllllllgggggggk......',
      '.....kggggggggggggggggggllllllllllllggggggggk.....',
      '....kggggggggggggggggggggllllllllllggggggggggk....',
      '....kggggggggggggggggggggggllllllggggggggggggk....',
      '....kggggggggggggggggggggggggggggggggggggggggk....',
      '...kggggllllllggggggggggggggggggggggggggggggggk...',
      '...kgggllllllllgggggggggggggggggggggggggggggggk...',
      '...kggllllllllllggggggggggggggggggggggggggggggk...',
      '...kggllllllllllgggggggggggggggggrrgggggggggggk...',
      '...kgggllllllllggggggggggggggggggrrgggggggggggk...',
      '...kggggllllllgggGGGGGGGGGGGGGGGGggggggggggggggk..',
      '...kggggggggGGrrGGGGGGGGGGGGGGGGGGGGGGgggggggggk..',
      '..kggggggGGGGGrrGGGGGGGGGGGGGGGGGGGGGGGGGgggggggk.',
      '..kggggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGrrGgggggk.',
      '..kgggGGGGGGGGGGGGGGGGrrGGGGGGGGGGGGGGGGrrGGggggk.',
      '..kggGGGGGGGGGGGGGGGGGrrGGGGGGGGGGGGGGGGGGGGGgggk.',
      '...kgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgk..',
      '...kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '....kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk...',
      '.....kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk....',
      '......kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkk.....',
      '.......kkkGGGGGGgGGGGGGGGGGGGGGGGgGGGGGGGkk.......',
      '..........kkkkbbbkkkggggggggggkkkkbbbbkkk.........',
      '.............kbbbbk.kbbbbbBBBk.kbbbbbbk...........',
      '.............kbbbbbkkbbbbbBBBkkbbbbbbk............',
      '..............kbbbbbkbbbbbBBBkbbbbbbk.............',
      '...............kbbbbbbbbbbBBBbbbbbbk..............',
      '................kbbbbbbbbbBBbbbbbbk...............',
      '.................kbbbbbbbbBbbbbbbk................',
      '..................kbbbbbbbBbbbbkk.................',
      '...................kbbbbbbBbbbk...................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '....................kbbbbbBBBk....................',
      '.................kkkkbbbbbBBBkkkk.................',
      '................kbbbbbbbbbbbbbbbbk................',
      '................kbbbbbbbbbbbbbbbbk................',
      '...............kbbbbbbbbbbbbbbbbbbk...............',
    ],
  },
  bananenboom: {
    palet: { k: '#23171a', b: '#8a6a45', B: '#6b4f31', g: '#5cab45', G: '#3f8a34', y: '#f7d23e', Y: '#d9a91e' },
    rijen: [
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '................................kk................',
      '.................k............kkggkkk.............',
      '..............kkkGkkkk..kkk..kgggggggk............',
      '.............kggggGGGGkkggGkkgggGGkkk.............',
      '..............kkggggggGkggGggggGkk................',
      '................kkkggkgGggggggGkkkkkkkkk..........',
      '.............kkkkkkkkgggggggggggggggggggk.........',
      '...........kkGGGGGGGGgGggGggggGggggggggggkkk......',
      '..........kGGggggggggggGGGgggggGGGGGGGGGGgggkk....',
      '.......kkkgggggggggggggGGgggggGGkkkkkkkkkkkkggk...',
      '......kgggkgkkkkkkkkkGGgggGGggggk...........kk....',
      '.....kgkkk.k.......kGgggggGGbbGggk................',
      '......k...........kGggkggbyybbyyggk...............',
      '.................kGggk.kBByyyyyyGggk..............',
      '................kGggk..kbbyyYyyYkGggk.............',
      '...............kGggk...kbyyyyyyyykGggk............',
      '...............kggk....kbyyyyyyyykkGgk............',
      '..............kggk.....kbyyYyYyyYk.kGgk...........',
      '.............kgkk.......kBBbyyykk...kkgk..........',
      '.............kk.........kbbbyyyk......kk..........',
      '............kgk.........kbbbyyYk......kgk.........',
      '.............k..........kbbbbbk........k..........',
      '........................kbbbbbk...................',
      '........................kBBbbbk...................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kBBbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kBBbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kBBbbbk..................',
      '.........................kbbbbbk..................',
      '.........................kbbbbbk..................',
      '........................kbbbbbk...................',
      '........................kbbbbbk...................',
      '........................kBBbbbk...................',
      '........................kbbbbbk...................',
      '........................kbbbbbk...................',
      '........................kbbbbbk...................',
      '.......................kbbbbbk....................',
      '.......................kBBbbbk....................',
      '.......................kbbbbbk....................',
      '.......................kbbbbbk....................',
      '.......................kbbbbbk....................',
      '......................kbbbbbk.....................',
      '......................kBBbbbk.....................',
      '......................kbbbbbk.....................',
    ],
  },
  vijver: {
    palet: { k: '#23171a', s: '#8e9199', S: '#b9bcc4', w: '#3f86c9', W: '#2c679f', l: '#9fd0f5', r: '#4f8a3a', R: '#8a5a2e' },
    rijen: [
      '............................................................................................................',
      '......................................................................................................k.....',
      '......k..............................................................................................kRk....',
      '.....kRk....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................kRk....',
      '.....kRk..........kkkkkkkkkksssssssssssssssssssssssssssssssssssssssssssssssssssskkkkkkkkkk..........kkrk....',
      '....kkrk....kkkkkksssssssssssSsssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssSsssskkkkkk...kRkrk....',
      '...kRkrkkkkkssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssSssskkkkRkrkk...',
      '...kRkrsRsssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssrkrkRk..',
      '..kkrsrsRwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsrsrsRk..',
      '.kssrsrwrwwwwwwwwwwwllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwrsrsk.',
      'ksssrwrwrwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwwwwwwwwwwwrwrwrssk',
      'ksssrwrwrwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWllllllWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwrwrwrssk',
      '.kssrsrwrwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWllllllWWWWWWWWWWWWwwrwrsrsk.',
      '..kkrsrsrWWWWWWWWWWWWWWWWWWWWWWWllllllWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWsrsrsrk..',
      '...krkrsrssssWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWsssssrkrkrk..',
      '...krkrkrkkksssssssssWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWssssssssskkkkrkrkrk..',
      '....k.k.k...kkkkkkssssssssssssssssWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWsssssssssssssssskkkkkk....k.k.k...',
      '..................kkkkkkkkkksssssssssssssssssssssssssssssssssssssssssssssssssssskkkkkkkkkk..................',
    ],
  },
  bloemen: {
    palet: { k: '#23171a', s: '#4f9a4a', p: '#ff7eb3', y: '#ffd23f', w: '#f7f3ea', v: '#b58cff', h: '#f5a524' },
    rijen: [
      '............................................',
      '............................................',
      '............................................',
      '............................................',
      '...........................k................',
      '.........k...............kkpkk..............',
      '.......kkykk............kpppppk..k..........',
      '......kyyyyyk..k........kpphppkkkykk........',
      '......kyyhyykkkwkk......kpppppkyyyyyk..k....',
      '......kyyyyykwwwwwk..k...kkpkkkyyhyykkkvkk..',
      '...k...kkykkkwwhwwkkkvkk..ksk.kyyyyykvvvvvk.',
      '.kkpkk..ksk.kwwwwwkvvvvvk.ksk..kkykkkvvhvvk.',
      'kpppppk.ksk..kkwkkkvvhvvk.ksk...ksk.kvvvvvk.',
      'kpphppk.ksk...ksk.kvvvvvk.ksk...ksk..kkvkk..',
      'kpppppk.ksk...ksk..kkvkk..ksk...ksk...ksk...',
      '.kkpkk..ksk...ksk...ksk...ksk...ksk...ksk...',
      '..ksk...kskk..ksk...kskk..ksk...kskk..ksk...',
      '..ksk...ksssk.ksk...ksssk.ksk...ksssk.ksk...',
      '..ksk...ksssk.ksk...ksssk.ksk...ksssk.ksk...',
      '..ksk...kskk..ksk...kskk..ksk...kskk..ksk...',
      '..ksk...ksk...ksk...ksk...ksk...ksk...ksk...',
      '..ksk...ksk...ksk...ksk...ksk...ksk...ksk...',
    ],
  },
  moestuin: {
    palet: { k: '#23171a', a: '#6b4423', A: '#87603a', o: '#f58a2a', g: '#4f9a4a', G: '#6cbf4f', l: '#a6e07a' },
    rijen: [
      '............................................',
      '............................................',
      '............................................',
      '.......k.......k...............k.......k....',
      '....k.kgkk..k.kgkk..kkkk....k.kgkk..k.kgkk..',
      '...kgkkgkgkkgkkgkgkkGGGGkk.kgkkgkgkkgkkgkgk.',
      '...kggkgggkkggkgggGGllllGGkkggkgggkkggkgggk.',
      '....kgkggk..kgkggkGGllllGGk.kgkggk..kgkggk..',
      '....kgkggk..kgkggGGGllllGGGkkgkggk..kgkggk..',
      '....kggggk..kggggkGGllllGGkkkggggk..kggggk..',
      '.....kggkkkkaaggaaGGGGGGGGaaaaggkkkkkkggk...',
      '...kkkooAAAAAAooAAAAGGGGAAAAAAooAAAAAaook...',
      '.kkAAAooAAAAAAooAAAAAAAAAAAAAAooAAAAAAooAkk.',
      'kaaaaaooAAAAAAooAAAAAAAAAAAAAAooAAAAAaooaaak',
      'kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak',
      '.kkaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaakk.',
    ],
  },
  hol: {
    palet: { k: '#23171a', a: '#7a5234', A: '#9a6d45', z: '#1c120c' },
    rijen: [
      '......................',
      '......................',
      '......kkkkkkkkkk......',
      '....kkaaaaaaaaaakk....',
      '..kkAaaaaAaaaaaAaakk..',
      '.kaaaaaaaaaaaaaaaaaak.',
      'kaaaaaaazzzzzzaaaaaaak',
      'kaaaaazzzzzzzzzzaaaaak',
      'kaaaaazzzzzzzzzzaaaaak',
    ],
  },
  cactus: {
    palet: { k: '#23171a', g: '#4f9a4a', G: '#3a7a37', l: '#9ad07a', p: '#ff7eb3' },
    rijen: [
      '.........kkk..........',
      '........kpppk.........',
      '........kpppk.........',
      '........kpppk.........',
      '.......kgpppgk........',
      '.......kgggggk........',
      '......kgggggGGk.......',
      '.......kggggGGk.......',
      '.......kglglGGk.......',
      '.......kggggGGk.kkk...',
      '.......kggggGGkkgggk..',
      '.......kggggGGkkgggk..',
      '.......kglglGGkkggggk.',
      '..kkk..kggggGGkkggggk.',
      '.kgggk.kggggGGkkggggk.',
      '.kgggk.kggggGGkkggggk.',
      '.kggggkkglglGGkkggggk.',
      '.kglggkkggggGGkkglggk.',
      '.kggggkkggggGGkkggggk.',
      '.kggggkkggggGGkkggggk.',
      '.kggggkkglglGGkkggggk.',
      '.kglggkkggggGGkkglggk.',
      '.kggggkkggggGGggggggk.',
      '.kggggkkggggGGggggggk.',
      '.kggggkkglglGGggggggk.',
      '.kggggkkggggGGggggggk.',
      '.kggggggggggGGkkkkkk..',
      '.kggggggggggGGk.......',
      '.kggggggglglGGk.......',
      '.kggggggggggGGk.......',
      '..kkkkkkggggGGk.......',
      '.......kggggGGk.......',
      '.......kglglGGk.......',
      '.......kggggGGk.......',
      '.......kggggGGk.......',
      '.......kggggGGk.......',
      '.......kglglGGk.......',
      '.......kggggGGk.......',
      '.......kggggGGk.......',
      '.......kggggGGk.......',
    ],
  },
};
